import { Albert_Sans } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Bravura group",
  description: "Generated by create next app",
};
const albert_init = Albert_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-albert",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </head>
      <body className={albert_init.variable}>{children}</body>
    </html>
  );
}
